name: Cypress Tests Parallelism

on: push

jobs:
  Cypress-run-getting1:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout project
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    -
      name: "Install dependencies"
      run: "npm ci"
    -
      name: "Run tests"
      run: "npm run cy:getting1"

  Cypress-run-advance2:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout project
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    -
      name: "Install dependencies"
      run: "npm ci"
    -
      name: "Run tests"
      run: "npm run cy:advance2"

  Cypress-run-advance3:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout project
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    -
      name: "Install dependencies"
      run: "npm ci"
    -
      name: "Run tests"
      run: "npm run cy:advance3"

  Cypress-run-advance4:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout project
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    -
      name: "Install dependencies"
      run: "npm ci"
    -
      name: "Run tests"
      run: "npm run cy:advance4"
